---
- hosts: aws_debian
  remote_user: "inser user here"
  become: true
  roles:
    - basic
  vars_files:
    - vars.yaml
  vars:
    ansible_ssh_private_key_file: "{{ key1 }}"
  tasks:
    - name: Echo a hello message
      command: echo hello
